#!/usr/bin/env node
var app = require('./app_node/app');
app.set('port', process.env.PORT || 3001);
var server = app.listen(app.get('port'),
  function() {
    console.log('RESTbox controller is listening on port ' + server.address().port);
  }
);
